apiVersion: v2
name: fluent-bit-crds
description: A Helm chart delivering fluent-bit controller CRDS
keywords:
  - logging
  - fluent-bit
  - operator
version: 3.1.0
appVersion: "3.1.0"
sources:
  - https://github.com/fluent/fluent-operator
maintainers:
  - name: wenchajun
    email: dehaocheng@kubesphere.io
