{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
{{- if .Values.fluentbit.serviceMonitor.enable -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit
  namespace: {{ template "fluent-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: fluent-bit
    {{- with .Values.fluentbit.serviceMonitor.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      path: {{ .Values.fluentbit.serviceMonitor.path }}
      {{- if .Values.fluentbit.serviceMonitor.secure }}
      scheme: https
      {{- if .Values.fluentbit.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.fluentbit.serviceMonitor.tlsConfig }}
      {{- end }}
      {{- end }}
      interval: {{ .Values.fluentbit.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.fluentbit.serviceMonitor.scrapeTimeout }}
      {{- with .Values.fluentbit.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.fluentbit.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      {{- with .Values.fluentbit.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ template "fluent-operator.namespace" . }}
{{- end }}
{{- end }}
{{- end }}
