apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit-collector.scriptsConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-collector.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.luaScripts }}
  {{ $k }}: |-
{{- (tpl $v $) | nindent 4 }}
{{- end }}
