apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluent-bit-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-collector.labels" . | nindent 4 }}
spec:
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fluent-bit-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fluent-bit-collector.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if or (not .Values.hotReload.enabled) .Values.podAnnotations }}
      annotations:
      {{- if not .Values.hotReload.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap-config.yaml") . | sha256sum }}
      {{- if .Values.luaScripts }}
        checksum/scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
      {{- end }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fluent-bit-collector.serviceAccountName" . }}
    {{- if ne .Values.automountServiceAccountToken nil }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
    {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
    {{- end }}
      containers:
        - name: collector
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "fluent-bit-collector.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- range $p := .Values.service.additionalPorts }}
            - name: {{ printf "ADDITIONAL_PORT_%s" (upper $p.name | replace "-" "_") }}
              value: {{ quote $p.containerPort }}
          {{- end }}
            - name: CONFIG_PATH
              value: /fluent-bit/etc/conf
          {{- if .Values.storage.enabled }}
            - name: STORAGE_PATH
              value: /fluent-bit/data
          {{- end }}
          {{- if .Values.config.luaScripts }}
            - name: SCRIPTS_PATH
              value: /fluent-bit/scripts
          {{- end }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.yaml
          {{- if .Values.hotReload.enabled }}
            - --enable-hot-reload
          {{- end }}
          {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          {{- range .Values.service.additionalPorts }}
            - name: {{ .name }}
              containerPort: {{ default .port .containerPort }}
              protocol: {{ default "TCP" .protocol }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/conf
          {{- if or .Values.hotReload.enabled .Values.luaScripts }}
            - name: scripts
              mountPath: /fluent-bit/scripts
          {{- end }}
          {{- range .Values.hostVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
          {{- end }}
          {{- if .Values.storage }}
            - name: data
              mountPath: /fluent-bit/data
              readOnly: false
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.hotReload.enabled }}
        - name: reloader
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
          image: {{ include "fluent-bit-collector.reloaderImage" . }}
          imagePullPolicy: {{ .Values.hotReload.image.pullPolicy }}
          args:
            - {{ printf "-webhook-url=http://localhost:%s/api/v2/reload" (toString .Values.service.httpPort) }}
            - -volume-dir=/watch/config
            - -volume-dir=/watch/scripts
          {{- range $idx, $val := .Values.hotReload.extraWatchVolumes }}
            - {{ printf "-volume-dir=/watch/extra-%d" (int $idx) }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /watch/config
            - name: scripts
              mountPath: /watch/scripts
          {{- range $idx, $val := .Values.hotReload.extraWatchVolumes }}
            - name: {{ $val }}
              mountPath: {{ printf "/watch/extra-%d" (int $idx) }}
          {{- end }}
          {{- with .Values.hotReload.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fluent-bit-collector.configConfigMapName" . }}
      {{- if or .Values.hotReload.enabled .Values.luaScripts }}
        - name: scripts
          configMap:
            name: {{ include "fluent-bit-collector.scriptsConfigMapName" . }}
      {{- end }}
      {{- range .Values.hostVolumes }}
        - name: {{ .name }}
          hostPath:
            {{- toYaml .hostPath | nindent 12 }}
      {{- end }}
      {{- if .Values.storage }}
        - name: data
          hostPath:
            path: {{ .Values.storage.hostPath }}
            type: DirectoryOrCreate
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
