apiVersion: v1
name: fluent-bit
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
  - fluentd
version: 0.4.0
appVersion: 1.4.6
icon: https://fluentbit.io/assets/img/logo1-default.png
home: https://fluentbit.io/
sources:
  - https://github.com/fluent/fluent-bit/
maintainers:
  - name: edsiper
    email: eduardo@treasure-data.com
  - name: naseemkullah
    email: naseem@transit.app
  - name: Towmeykaw
    email: towmeykaw@gmail.com
