apiVersion: v1
name: fluent-bit
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
  - fluentd
version: 0.53.0
appVersion: 4.0.7
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/fluentd/fluentbit/icon/fluentbit-icon-color.svg
home: https://fluentbit.io/
sources:
  - https://github.com/fluent/fluent-bit/
maintainers:
  - name: edsiper
    email: eduardo@calyptia.com
  - name: naseemkullah
    email: naseem@transit.app
  - name: Towmeykaw
    email: towmeykaw@gmail.com
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Make securityContext of hot reload container configurable in fluent-bit chart"
