apiVersion: v2
name: fluentd-crds
description: A Helm chart delivering fluentd controller CRDS
keywords:
  - logging
  - fluentd
  - operator
version: 3.1.0
appVersion: "3.1.0"
sources:
  - https://github.com/fluent/fluent-operator
maintainers:
  - name: wenchajun
    email: dehaocheng@kubesphere.io
