name: Close stale issues and PR(s)
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  stale:
    name: Mark stale
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 5 days. Maintainers can add the `exempt-stale` label.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 90
          days-before-close: 5
          days-before-pr-close: -1
          exempt-all-pr-assignees: true
          exempt-all-pr-milestones: true
          exempt-issue-labels: 'long-term,enhancement,exempt-stale'
          # start with the oldest
          ascending: true
          # keep an eye on this
          operations-per-run: 250
